version: "3.9"

services:
  db:
    image: mariadb:lts
    command: --transaction-isolation=READ-COMMITTED
    restart: always
    volumes:
      - /home/tristans/data/db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=Root_12345
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env
    networks:
      - internal
      - caddy-network

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal
      - caddy-network

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /home/tristans/data/nextcloud:/var/www/html:z
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=172.22.0.0/16
      - OVERWRITEHOST=tshomeserv.duckdns.org
      - OVERWRITEPROTOCOL=https
      - FORWARDED_FOR_HEADERS=HTTP_X_FORWARDED_FOR,HTTP_X_FORWARDED_PROTO,HTTP_X_FORWARDED_HOST,HTTP_X_FORWARDED_PORT
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - internal
      - caddy-network

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /home/tristans/data/nextcloud:/var/www/html:z
      # must match with volume config of app container
    entrypoint: /cron.sh
    depends_on:
      - app
      - redis
      - db
    networks:
      - internal
      - caddy-network

networks:
  internal:
    driver: bridge
  caddy-network:
    external: true
