services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /home/tristans/data/nextcloud:/mnt/ncdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NEXTCLOUD_DATADIR: /mnt/ncdata
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 127.0.0.1
      SKIP_DOMAIN_VALIDATION: "true"
    network_mode: bridge
    # No need to expose 80/443 publicly; Caddy handles HTTPS
    ports:
      - 8080:8080

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
